version: "2"
services:
  php:
    build: phpfpm/
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
    environment:
       - BLACKFIRE_CLIENT_ID
       - BLACKFIRE_CLIENT_TOKEN
       - BLACKFIRE_SERVER_ID
       - BLACKFIRE_SERVER_TOKEN
       - BLACKFIRE_LOG_LEVEL=4
